version: 0
allowPullRequests: public
metadata:
  name: terraform-provider-jsone
  description: 'Test the terraform provider for json-e'
  owner: '{{ event.head.user.email }}'
  source: '{{ event.head.repo.url }}'
tasks:
  - provisionerId: '{{ taskcluster.docker.provisionerId }}'
    workerType: '{{ taskcluster.docker.workerType }}'
    extra:
      github:
        events:
          - pull_request.opened
          - pull_request.synchronize
          - pull_request.reopened
          - push
        branches:
          - master
    payload:
      maxRunTime: 3600
      image: 'golang:1.9-stretch'
      command:
        - /bin/bash
        - '-c'
        - >-
          mkdir -p /go/src/github.com/taskcluster/terraform-provider-jsone &&
          cd /go/src/github.com/taskcluster/terraform-provider-jsone &&
          git clone {{event.head.repo.url}} . &&
          git config advice.detachedHead false &&
          git checkout {{event.head.sha}} &&
          go get -v -d -t ./... &&
          go test -v -race ./...
    metadata:
      name: terraform-provider-jsone go test
      description: Run library test suite - golang 1.9
      owner: '{{ event.head.user.email }}'
      source: '{{ event.head.repo.url }}'
